# Ejemplo de conexion a base de datos
# Se necesita crear archivo "database.properties" en la misma carpeta y
# reemplazar los valores por los de tu base de datos

db.url=jdbc:postgresql://localhost:5432/distribucion 
db.user=USUARIO
db.password=PASSWORD